
name: HuggingFace Space Sync

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  push-hf-space:
    name: Push source code to HuggingFace
    runs-on: ubuntu-latest

    steps:
      - name: Sync to HuggingFace
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: 'xiaoyao9184/space-wam'
          huggingface_repo_id: '${{ secrets.HF_USERNAME }}/watermark-anything'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
